services:
  consul:
    image: hashicorp/consul
    container_name: git-check-consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: ["consul", "agent", "-dev", "-bootstrap-expect=1", "-ui", "-client=0.0.0.0", "-log-level=ERROR"]
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - msa-network

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GATEWAY_PORT: 8080
    container_name: git-check-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS=always
    depends_on:
      consul:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - msa-network

networks:
  msa-network:
    external: true